# fly.toml app configuration file generated for fragrant-dew-6080 on 2023-08-16T20:46:19-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fragrant-dew-6080"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="db"
  destination="/mnt/db"